spring:
  application:
    name: sigo-web-api
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    open-in-view: false
    database-platform:  org.hibernate.dialect.H2Dialect
    show-sql: true
  jackson:
    deserialization:
       fail-on-unknown-properties: true
    date-format: yyyy-MM-dd

server:
  port: 8091

sigo-ms-endpoints-uri:
  gca: http://ec2-3-142-199-202.us-east-2.compute.amazonaws.com:8090/
  gpi: http://ec2-3-17-159-179.us-east-2.compute.amazonaws.com:8090/
  standard: http://ec2-3-137-204-36.us-east-2.compute.amazonaws.com:8090/

logging:
  config: src/main/resources/logback-dev.xml