spring:
  application:
    name: gpi-manager

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform:  org.hibernate.dialect.H2Dialect

server:
  port: 8090

logging:
  config: src/main/resources/logback-dev.xml
